### PR TITLE
Update mainnet peers

### PR DESCRIPTION
**Pull request by llybin**
All P2P.BootstrapPeers on port 8123.

`select announced_address from scan_peermonitor where availability > 90 and version in ("v2.5.0", "v2.5.1") and height >= 772324 and created_at < "2020-01-01";`

I've removed two unavailable IP from P2P.rebroadcastTo.

https://github.com/burst-apps-team/burstcoin/issues/11

### CODE REVIEW

**Comment by llybin** [comment]
Guys, what you think about increase P2P.NumBootstrapConnections? Theoretically, if more nodes are connected to the same peers, it should be better. We have a trouble near it. Also what you think if add into rebroadcast top of public peers, it may also affect.

As far as I understand currently rebroadcast is synchronous, correct me pls, if to make it parallel also I think we can increase connectedness.

**Comment by jjos2372** [comment]
About the `P2P.NumBootstrapConnections` it is the minimum number of bootstrap nodes you are connected before connecting to other nodes not in the bootstrap list (those other peers forwarded to you). So, if this number is high, let's say 10, and you are unable to connect to more than 10 bootstrap nodes (say 8) then you will be stuck with those 8 nodes.

**Comment by Zoh63392187** [comment]
I see quite a few not connectable on tcp/8123 even that they run a node.

**Comment by llybin** [comment]
> few not connectable on tcp/8123
They despise you

Did you saw sql query? The main idea, most nodes should be actual even after 12 days.

**Comment by Zoh63392187** [comment]
No need to be toxic @llybin 
You have duplicate entrys in P2P.BootstrapPeers as peers are already in P2P.rebroadcastTo. 
(Maby don't remove " so no need for duplicates)
Also one of the rebroadcastTo is not there. I contacted the owner for a status / to bring it online.

**Pull request closed without merging**
