### PR TITLE
Create contribution rules

### PR DESCRIPTION
**Pull request by harry1453**

### CODE REVIEW

**Comment by blankey1337** [comment]
Thanks for kicking this off! Should we PR to `develop` instead of `master`? Given the likelihood of future hard forks, a `develop` branch might come in handy. If we do go with a `develop` branch, we'd branch off that when creating releases.
The username-in-branch rule is neat, I haven't seen that before, but I kinda like it :D.

**Comment by harry1453** [comment]
Yeah it's mainly for when we have like 20 branches it makes sure we know who owns what and who's responsible for what :)

**Comment by blankey1337** [comment]
That typically shouldn't happen if people fork first.

**Comment by harry1453** [comment]
Yeah but for our team it's easier to keep track of things if we are just using branches in the repository, which I personally prefer over forking and then merging, deleting the fork, recreating the fork when making new code etc.

**Comment by blankey1337** [comment]
You never have to delete your fork, just use remotes. https://help.github.com/articles/adding-a-remote/. Please don't push random branches to the team org.

**Pull request merged**
